# Generated by Django 5.1.3 on 2024-11-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobConet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_clave', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
