# Generated by Django 5.1.3 on 2024-11-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobConet_app', '0002_busquedatrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busquedatrabajo',
            name='palabra_clave',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
